src/UserBundle/Entity/CustomerOrder.php
<?php

namespace UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * CustomerOrder
 *
 * @ORM\Table(name="customer_order")
 * @ORM\Entity(repositoryClass="UserBundle\Repository\CustomerOrderRepository")
 */
class CustomerOrder
{

    const STATUS_OPEN = 1;
    const STATUS_DONE = 2;
    const STATUS_REJECT = 3;
    const STATUS_RESOLVE = 4;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="Date", type="datetime")
     */
    private $date;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;


    /**
     * @var Customer
     *
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\Customer", inversedBy="orders")
     * @ORM\JoinColumn(name="id_customer", referencedColumnName="id")
     */
    private $customer;

    /**
     * @var string
     *
     * @ORM\Column(name="phone_number", type="string", length=255, nullable=true)
     */
    private $phoneNumber;

    /**
     * @var string
     *
     * @ORM\Column(name="order_name", type="string", length=255, nullable=true)
     */
    private $orderName;

    /**
     * @return string
     */
    public function getOrderName()
    {
        return $this->orderName;
    }

    /**
     * @param string $orderName
     */
    public function setOrderName($orderName)
    {
        $this->orderName = $orderName;
    }



    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="UserBundle\Entity\OrderProduct", mappedBy="order", cascade={"all"})
     */
    private $products;

    /**
     * Add product
     *
     * @param \UserBundle\Entity\OrderProduct $product
     *
     * @return CustomerOrder
     */
    public function addProduct(\UserBundle\Entity\OrderProduct $product)
    {
        $product->setOrder($this);
        $this->products[] = $product;
        return $this;
    }
    /**
     * Remove product
     *
     * @param \UserBundle\Entity\OrderProduct $product
     */
    public function removeProduct(\UserBundle\Entity\OrderProduct $product)
    {
        $this->products->removeElement($product);
    }
    /**
     * Get products
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getProducts()
    {
        return $this->products;
    }


    public function __construct()
    {
        $this->setDate(new \DateTime("now"));
        $this->setStatus(self::STATUS_OPEN);
        $this->products = new ArrayCollection();

    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return CustomerOrder
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    public function getTotalPrice()
    {
        $total = 0;
        /** @var OrderProduct $product */
        foreach ($this->products as $product) {
            $total = $total + ( $product->getPrice() * $product->getCount());
        }
        return $total;
    }


    public function getTotalCount()
    {
        $total = 0;
        /** @var OrderProduct $product */
        foreach ($this->products as $product) {
            $total = $total + ( $product->getCount() );
        }
        return $total;
    }



    /**
     * Set status
     *
     * @param integer $status
     *
     * @return CustomerOrder
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }
    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }


    /**
     * Set customer
     *
     * @param \UserBundle\Entity\Customer $customer
     *
     * @return CustomerOrder
     */
    public function setCustomer(\UserBundle\Entity\Customer $customer = null)
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get customer
     *
     * @return \UserBundle\Entity\Customer
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * @param string $phoneNumber
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;
    }
}

src/UserBundle/Controller/BasketController.php
<?php


namespace UserBundle\Controller;


use UserBundle\Entity\Customer;
use UserBundle\Entity\CustomerOrder;
use UserBundle\Entity\OrderProduct;
use UserBundle\Entity\Product;
use UserBundle\Form\CustomerOrderType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class BasketController extends Controller
{
    /**
     * @Template
     */
    public function indexAction()
    {

        $manager = $this->getDoctrine()->getManager();
        $customer = $this->getUser();
        $order = $manager->getRepository('UserBundle:CustomerOrder')->getOrCreateOrder($customer);
        return ['order' => $order] ;
    }

    /**
     * @Template
     */
    public function historyOrderAction()
    {
        $customer = $this->getUser();
        $orders = $this->getDoctrine()->getRepository("UserBundle:CustomerOrder")->findBy(["customer" => $customer]);
        return ['orders' => $orders];

    }

    public function recalculationCurrentOrderAction(Request $request)
    {
        $manager = $this->getDoctrine()->getManager();
        $customer = $this->getUser();
        $order = $manager->getRepository('UserBundle:CustomerOrder')->getOrCreateOrder($customer);
        $products = $order->getProducts();
        /** @var OrderProduct $product */
        foreach ($products as $product)
        {
            $key = "prod_" . $product->getId();
            $productCount = $request->get($key);
            $productCount = intval($productCount);
            if ($productCount < 0) {
                $product->setCount(1);
            }
            elseif ($productCount == 0) {
                $this->orderRemoveProductAction($product);
            }
            else {
                $product->setCount($productCount);
            }
        }
        $manager->persist($order);
        $manager->flush();

        return $this->redirectToRoute("user_homepage.som");
    }

    public function orderRemoveProductAction(OrderProduct $orderProduct)
    {
        $manager = $this->getDoctrine()->getManager();
        $manager->remove($orderProduct);
        $manager->flush();
        return $this->redirectToRoute("user_homepage.som");
    }


    /**
     * @Template()
     */
    public function orderProductsAction(CustomerOrder $order)
    {
        $products = $order->getProducts();
        foreach ($products as $prod)
        {
            $productShop = $this->getDoctrine()->getRepository("UserBundle:Product")->find($prod->getIdProduct());
            if ($productShop == null) {
                $prod->setIdProduct(null);
            }
        }
        return ['order' => $order];
    }



    public function addProductToBasketAction($idProduct)
    {
        $manager = $this->getDoctrine()->getManager();
        $customer = $this->getUser();
        $order = $manager->getRepository('UserBundle:CustomerOrder')->getOrCreateOrder($customer);
        $dql = 'select p from UserBundle:OrderProduct p where p.order = :orderCustomer and p.idProduct = :idProduct';
        /** @var OrderProduct $productOrder */
        $productOrder = $manager->createQuery($dql)->setParameters([
            'idProduct' => $idProduct,
            'orderCustomer' => $order
        ])->getOneOrNullResult();
        if ($productOrder !== null)
        {
            $count = $productOrder->getCount();
            $productOrder->setCount($count + 1);
            $manager->persist($productOrder);
            $manager->flush();
            return $this->redirectToRoute('user_homepage.som');
        }
        else {
            $productShop = $manager->getRepository("UserBundle:Product")->find($idProduct);
            $productOrder = new OrderProduct();
            $productOrder->setCount(1);
            $productOrder->setModel($productShop->getProductName());
            $productOrder->setPrice($productShop->getPrice());
            $productOrder->setIdProduct($productShop->getId());
            $productOrder->setOrder($order);
            $manager->persist($productOrder);
            $manager->flush();
            return $this->redirectToRoute('user_homepage.som');
        }
    }

    public function confirmAction(Request $request)
    {
        $manager = $this->getDoctrine()->getManager();
        $customer = $this->getUser();
        $order = $manager->getRepository('UserBundle:CustomerOrder')->getOrCreateOrder($customer);
        $form = $this->createForm(CustomerOrderType::class, $order);
        if ($request->isMethod("POST"))
        {
            $form->handleRequest($request);
            $order->setStatus(CustomerOrder::STATUS_DONE);
            $manager->persist($order);
            $manager->flush();
            return $this->redirectToRoute("user_homepage.som");
        }
        return $this->render('@User/Basket/confirm.html.twig',[  'form' => $form->createView(),
            'order' => $order
        ]);



    }

    public function BasketNewAction()
    {
        return $this->render('UserBundle:Default:basket.html.twig');
    }

}

src/UserBundle/Resources/views/Basket/confirm.html.twig
{% extends '@User/Default/try.html.twig' %}
{% block categ %}

    <div>
        <b>Корзина товаров</b><br />
<table>
        <ul>

            {% for product in order.products %}

                Модель :<a href="{{ path("user_homepage.show_product_ID",{id:product.getId()})  }} " > {{ product.model  }} </a>- {{ product.price }} грн </br>

                Количество :
                {{ product.count }} штук(а) </br>
                {% set sum = product.count * product.price %}
                Сумма : {{ sum }} грн </br>

            {% endfor %}
        </ul>
</table>
        <form method="POST" action="{{ path('user_homepage.basket_confirm') }}">
            {{ form_widget(form) }}
            <input type="submit" value="Подтвердить заказ" />
        </form>
    </div>
{% endblock %}

src/UserBundle/Resources/views/Basket/historyOrder.html.twig
{% extends '@User/Default/try.html.twig' %}
{% block categ %}

    <div>
        <b>История ваших заказов</b><br />

        <table border="1">
            {% for order in orders %}
                <tr>
                    <td>{{ order.date.format("H:i d.m.Y") }}</td>
                    <td>{{ order.phoneNumber }}</td>
                    <td>
                        {% if order.status == 1 %}
                            в процессе
                        {% elseif order.status == 2 %}
                            обработан
                        {% else %}
                            отклонен
                        {% endif %}
                    </td>
                    <td>
                Общая стоимость : {{ order.totalPrice }}
                    </td>
                    <td>
                <a href="{{ path('user_homepage.orders_info', {id:order.id}) }} ">Детали</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    </div>

{% endblock %}

src/UserBundle/Resources/views/Basket/index.html.twig
<span class="basket">
		<img src="/Photos/cash.png" alt="cash">
		<span class="basket-num">{{ order.totalCount }}</span>
		<span class="basket-menu">
				<span class="basket-menu-triangle"></span>
				<ul class="basket-menu-item">
					{% if order.products|length > 0 %}
                    {% for product in order.products %}
						<li>  <a href="{{ path('user_homepage.show_product_ID', {id:product.idProduct}) }}" style="color: white">{{ product.model }} </a> - {{ product.price }} грн  </br>
						Количество:	{{ product.count }} шт <a href="{{ path('user_homepage.delete_from_basket', {id:product.id}) }}" style="color: white">[X]</a> </li>
                    {% endfor %}
						<li> <a href="{{ path('user_homepage.basket_confirm') }} "  style="color: white">Оформить заказ</a></li>
                    {% else %}
						Ваша корзина пуста
                    {% endif %}
				</ul>
		</span>

	</span>

src/UserBundle/Resources/views/Basket/orderProducts.html.twig
{% extends '@User/Default/try.html.twig' %}
{% block categ %}


        <div>
            <b>Товары в заказе</b><br />

            <fieldset>
                <legend>{{ order.date.format('H:i d.m.Y') }} - {{ order.phoneNumber }}</legend>

                <table border="1">
                    {% for product in order.products %}
                        <tr>
                            <td>
                                {% if product.idProduct is not null %}
                                    Наименование модели :
                                    <a href="{{ path('user_homepage.show_product_ID', {id:product.idProduct}) }}">
                                        {{ product.model }}
                                    </a>
                                {% else %}
                                    {{ product.model }}
                                {% endif %}
                            </td>
                            <td>
                              Цена:   {{ product.price }}
                            </td>
                            <td>
                              Количество:  {{ product.count }}
                            </td>
                            <td>

                            </td>
                        </tr>


                    {% endfor %}
                </table>
                Итоговая сумма заказа :  {{ order.getTotalPrice() }}
            </fieldset>

        </div>


{% endblock %}

src/UserBundle/Resources/views/Basket/recalculationCurrentOrder.html.twig
<div>
    <b>Корзина товаров</b><br />

    {% if order.products|length > 0 %}
        <form method="post" action="{{ path('user_homepage.basket_recalculation') }}">
            <ul>
                {% for product in order.products %}
                    {% set sum = product.price * product.count %}
                    <li><a href="{{ path('user_homepage.delete_from_basket', {id:product.id}) }}">[X]</a><b>{{ product.model }}</b> {{ product.price }}x
                        <input name="prod_{{ product.id }}" style="width: 20px" type="text" value="{{ product.count }}" />
                        ={{ sum }}</li>
                {% endfor %}
            </ul>
            <br>
            <input type="submit" value="Пересчитать" />
        </form>
        <a href="{{ path('user_homepage.basket_confirm') }}">Оформить заказ</a>
    {% endif %}

    <br>
    <a href="{{ path('user_homepage.orders_history') }}">История заказов</a>
</div>